### ISSUE TITLE
Plugin fails when git author contains an apostrophe

### ISSUE THREAD

**Issue by JohT** [kontext-e/jqassistant-git-plugin#2]
## Summary

Since version 2.2.1, the git plugin tries to execute the following query and fails:
```cypher
MATCH (a:Author) where a.identString = 'Forename O'Leary <forename.oleary@something.com>' return a
```
```
Invalid input 'Leary': expected an expression, 'FOREACH', 'CALL', 'CREATE', 'LOAD CSV', 'DELETE', 'DETACH', 'FINISH', 'INSERT', 'MATCH', 'MERGE', 'NODETACH', 'OPTIONAL', 'REMOVE', 'RETURN', 'SET', 'UNION', 'UNWIND', 'USE', 'WITH' or <EOF> (line 1, column 48 (offset: 47))
```

I assume the reason for that is that the name contains an apostrophe (').
Version 2.1.0 works fine.

## Context

- **Group-id:** de.kontext-e.jqassistant.plugin
- **Artifact-id:** jqassistant.plugin.git
- **Version:** 2.2.1
- **Java distribution:** adopt
- **Java version:** 17.0.12+7
- **Failed version update pull request:** https://github.com/JohT/code-graph-analysis-pipeline/pull/219
- **Reproduce:** Run jQAssistant with this git plugin on a clone of https://github.com/remix-run/react-router

## Idea

It seems that [jQAssistantGitRepository.java](https://github.com/kontext-e/jqassistant-git-plugin/blob/a38e8d5c61b04958bedc3ce57cc308d2ae969cee/src/main/java/de/kontext_e/jqassistant/plugin/git/scanner/JQAssistantGitRepository.java#L78) is a good starting point. It might already help to use query parameters (if possible) instead of string concatenation. Then neo4j should take care of escaping and it could also improve security and performance.

## Full Stack Trace

```
2024-10-08T17:42:17.1837789Z 2024-10-08 17:42:17.183 [main] WARN RemoteCypherQuery - Neo.ClientNotification.Statement.UnknownPropertyKeyWarning - The provided property key is not in the database: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: relativePath) (at 1:28)
2024-10-08T17:43:03.3969491Z ##[error]Exception in thread "main" com.buschmais.jqassistant.core.scanner.impl.UnrecoverableScannerException: Unexpected problem encountered while scanning: item='./source/react-router-6.26.2/.git/HEAD', path='/HEAD', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@2db6d68d, de.kontext_e.jqassistant.plugin.git.scanner.GitScannerPlugin@2f95653f]'. Please report this error including the full stacktrace (continueOnError=false).
2024-10-08T17:43:03.3973138Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:105)
2024-10-08T17:43:03.3974054Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:63)
2024-10-08T17:43:03.3975223Z 	at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:53)
2024-10-08T17:43:03.3976627Z 	at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainerScannerPlugin.scan(AbstractContainerScannerPlugin.java:29)
2024-10-08T17:43:03.3977761Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:125)
2024-10-08T17:43:03.3978648Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:84)
2024-10-08T17:43:03.3979503Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:63)
2024-10-08T17:43:03.3980600Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.scan(ScanTask.java:103)
2024-10-08T17:43:03.3981482Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$scanFiles$4(ScanTask.java:93)
2024-10-08T17:43:03.3982247Z 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
2024-10-08T17:43:03.3982971Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.scanFiles(ScanTask.java:83)
2024-10-08T17:43:03.3983819Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$run$0(ScanTask.java:61)
2024-10-08T17:43:03.3984585Z 	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
2024-10-08T17:43:03.3985342Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.lambda$run$2(ScanTask.java:60)
2024-10-08T17:43:03.3986643Z 	at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.withStore(AbstractStoreTask.java:50)
2024-10-08T17:43:03.3987547Z 	at com.buschmais.jqassistant.commandline.task.ScanTask.run(ScanTask.java:51)
2024-10-08T17:43:03.3988308Z 	at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:320)
2024-10-08T17:43:03.3989055Z 	at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:278)
2024-10-08T17:43:03.3990190Z 	at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:204)
2024-10-08T17:43:03.3990952Z 	at com.buschmais.jqassistant.commandline.Main.run(Main.java:82)
2024-10-08T17:43:03.3991598Z 	at com.buschmais.jqassistant.commandline.Main.main(Main.java:63)
2024-10-08T17:43:03.3992926Z Caused by: com.buschmais.xo.api.XOException: Cannot execute statement 'MATCH (a:Author) where a.identString = 'Forename O'Leary <forename.oleary@something.com>' return a', {}
2024-10-08T17:43:03.3994178Z 	at com.buschmais.xo.neo4j.remote.impl.datastore.StatementExecutor.execute(StatementExecutor.java:51)
2024-10-08T17:43:03.3995231Z 	at com.buschmais.xo.neo4j.remote.impl.datastore.RemoteCypherQuery.execute(RemoteCypherQuery.java:44)
2024-10-08T17:43:03.3996108Z 	at com.buschmais.xo.impl.query.XOQueryImpl.execute(XOQueryImpl.java:131)
2024-10-08T17:43:03.3997203Z 	at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.executeQuery(AbstractGraphStore.java:195)
2024-10-08T17:43:03.3998473Z 	at de.kontext_e.jqassistant.plugin.git.scanner.JQAssistantGitRepository.getAuthorDescriptorFromDB(JQAssistantGitRepository.java:79)
2024-10-08T17:43:03.3999767Z 	at de.kontext_e.jqassistant.plugin.git.scanner.cache.AuthorCache.find(AuthorCache.java:39)
2024-10-08T17:43:03.4000810Z 	at de.kontext_e.jqassistant.plugin.git.scanner.cache.AuthorCache.findOrCreate(AuthorCache.java:28)
2024-10-08T17:43:03.4001909Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitRepositoryScanner.addCommitForAuthor(GitRepositoryScanner.java:139)
2024-10-08T17:43:03.4003107Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitRepositoryScanner.storeCommitNodes(GitRepositoryScanner.java:125)
2024-10-08T17:43:03.4004291Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitRepositoryScanner.storeCommits(GitRepositoryScanner.java:116)
2024-10-08T17:43:03.4005417Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitRepositoryScanner.scanGitRepo(GitRepositoryScanner.java:58)
2024-10-08T17:43:03.4006445Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitScannerPlugin.scan(GitScannerPlugin.java:100)
2024-10-08T17:43:03.4007391Z 	at de.kontext_e.jqassistant.plugin.git.scanner.GitScannerPlugin.scan(GitScannerPlugin.java:26)
2024-10-08T17:43:03.4008302Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:125)
2024-10-08T17:43:03.4009180Z 	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:88)
2024-10-08T17:43:03.4010092Z 	... 20 more
2024-10-08T17:43:03.4011871Z Caused by: org.neo4j.driver.exceptions.ClientException: Invalid input 'Leary': expected an expression, 'FOREACH', 'CALL', 'CREATE', 'LOAD CSV', 'DELETE', 'DETACH', 'FINISH', 'INSERT', 'MATCH', 'MERGE', 'NODETACH', 'OPTIONAL', 'REMOVE', 'RETURN', 'SET', 'UNION', 'UNWIND', 'USE', 'WITH' or <EOF> (line 1, column 48 (offset: 47))
2024-10-08T17:43:03.4013596Z "MATCH (a:Author) where a.identString = 'Forename O'Leary <forename.oleary@something.com>' return a"
2024-10-08T17:43:03.4014196Z                                                 ^
2024-10-08T17:43:03.4014778Z 	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111)
2024-10-08T17:43:03.4015566Z 	at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:58)
2024-10-08T17:43:03.4016385Z 	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34)
2024-10-08T17:43:03.4017206Z 	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:39)
2024-10-08T17:43:03.4018137Z 	at com.buschmais.xo.neo4j.remote.impl.datastore.StatementExecutor.execute(StatementExecutor.java:49)
2024-10-08T17:43:03.4018952Z 	... 34 more
2024-10-08T17:43:03.4019436Z 	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
2024-10-08T17:43:03.4020485Z 		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:76)
2024-10-08T17:43:03.4021559Z 		at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:107)
2024-10-08T17:43:03.4022842Z 		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.unpackFailureMessage(CommonMessageReader.java:75)
2024-10-08T17:43:03.4023998Z 		at org.neo4j.driver.internal.messaging.common.CommonMessageReader.read(CommonMessageReader.java:53)
2024-10-08T17:43:03.4025099Z 		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:81)
2024-10-08T17:43:03.4026229Z 		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:37)
2024-10-08T17:43:03.4027497Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
2024-10-08T17:43:03.4028966Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-10-08T17:43:03.4030706Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08T17:43:03.4032231Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08T17:43:03.4033656Z 		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2024-10-08T17:43:03.4034995Z 		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
2024-10-08T17:43:03.4036122Z 		at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:42)
2024-10-08T17:43:03.4037381Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-10-08T17:43:03.4038885Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08T17:43:03.4040504Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08T17:43:03.4041928Z 		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2024-10-08T17:43:03.4043252Z 		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
2024-10-08T17:43:03.4044667Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-10-08T17:43:03.4046177Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08T17:43:03.4047677Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08T17:43:03.4049046Z 		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
2024-10-08T17:43:03.4050529Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2024-10-08T17:43:03.4052023Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08T17:43:03.4053516Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08T17:43:03.4054956Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
2024-10-08T17:43:03.4056846Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2024-10-08T17:43:03.4058359Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08T17:43:03.4059898Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
2024-10-08T17:43:03.4061242Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2024-10-08T17:43:03.4062508Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
2024-10-08T17:43:03.4063769Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-10-08T17:43:03.4065048Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-10-08T17:43:03.4066289Z 		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-10-08T17:43:03.4067485Z 		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
2024-10-08T17:43:03.4068718Z 		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-10-08T17:43:03.4070034Z 		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-10-08T17:43:03.4070921Z 		at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by JohT** [comment]
Thank you very much @WilliamThimm 👍. 

I could now also positively verify it 🥳. 
I was able to update to the newest version 2.2.2 and there is no problem with authors having an apostrophe in their name.
